name: Direct Push Notifications

on:
  push:
    branches: [main]

jobs:
  notify:
    if: >-
      !startsWith(github.event.head_commit.message, 'Merge pull request')
    uses: interstellio/.github/.github/workflows/direct-push-notifications.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
