name: Direct Push Notifications

on:
  push:
    branches: [main]

jobs:
  notify:
    uses: interstellio/.github/.github/workflows/direct-push-notifications.yml@main
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
